<?php
class DBLog {
	
	/**
	 * The string used to query the database.
	 * @var string
	 */
	private $_queryString;
	
	/**
	 * The time, in seconds, between the unix epoch and the start of the query.
	 * @var float
	 */
	private $_startTime = 0.0;

	/**
	 * The time, in seconds, between the unix epoch and the first record being returned from the query.
	 * The value is 0.0 if there is no split time.
	 * @var float
	 */
	private $_splitTime = 0.0;
	
	/**
	 * The time, in seconds, between the unix epoch and the final record being returned from the query.
	 * This value is 0.0 if the query did not successfully complete.
	 * @var float
	 */
	private $_completeTime = 0.0;
	
	/**
	 * The error message generated by this query.  This value is null if there was no error.
	 * @var string
	 */
	private $_errorMessage = null;
	
	public function __construct($queryString) {
		$this->_queryString = $queryString;
		$this->_startTime = microtime(true);
	}
	
	public function split() {
		$this->_splitTime = microtime(true);
	}
	
	public function end() {
		$this->_completeTime = microtime(true);
		if ($this->_splitTime == 0.0)
			$this->_splitTime = $this->_completeTime;
	}
	
	public function error($message) {
		$this->_errorMessage = $message;
	}
	
	public function isCompleted() {
		return $this->_completeTime > 0.0;
	}
	
	public function getQueryString() {
		return $this->_queryString;
	}
	
	public function getCompleteTime() {
		return $this->_completeTime - $this->_startTime;
	}
	
	public function getSplitTime() {
		return $this->_splitTime - $this->_startTime;
	}
	
	public function getErrorMessage() {
		return $this->_errorMessage;
	}
}
